document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <link href=\'../css/nav-floor.css\' rel=\'stylesheet\'/>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'bottom_content\'>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");