document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <link href=\'../css/smallSearch.css\' rel=\'stylesheet\'/>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'content-top\'>");
document.writeln("    <div class=\'home_icon\'>");
document.writeln("        <a><img class=\'icon\' src=\'/image/HomeIcon.png\'></a>");
document.writeln("    </div>");
document.writeln("    <div class=\'seach_box\'>");
document.writeln("        <form action=\'search\' method=\'post\'>");
document.writeln("            <button id=\'search-btn\' type=\'submit\'>搜商品</button>");
document.writeln("            <input id=\'search-text\' type=\'text\' placeholder=\'这里有你想要的\'>");
document.writeln("        </form>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");